export const workers = [
  {
    id: "w1",
    name: "Ramesh Kumar",
    role: "Electrician",
    rating: 4.8,
    jobs: 287,
    distance: "2.1 km",
    eta: "5:30 PM",
    verified: { livePhoto: true, identity: true, coop: true, skill: true, bg: false },
    skills: ["Home wiring", "Fan repair", "Switch/socket installation", "Basic appliance repair"],
    experience: "5 years",
    languages: ["Hindi", "Bengali"],
    area: "Within 10 km",
    availability: "Today: 5 PM – 9 PM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "ABC Labour Cooperative",
    location: "Haldia",
    avatar: "RK",
    earnings: { today: 1250, week: 6800, month: 18400, jobs: 73, pending: 800 },
    welfare: { insurance: "Active", coverage: 500000, fund: 2400, trainings: 2, claims: 0 },
  },
  {
    id: "w2",
    name: "Sita Devi",
    role: "Maid",
    rating: 4.9,
    jobs: 412,
    distance: "0.8 km",
    eta: "8:00 AM",
    verified: { livePhoto: true, identity: true, coop: true, skill: true, bg: true },
    skills: ["House cleaning", "Cooking", "Laundry", "Ironing"],
    experience: "8 years",
    languages: ["Bengali", "Hindi"],
    area: "Within 5 km",
    availability: "Mon–Sat: 8 AM – 12 PM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "Mahila Labour Cooperative",
    location: "Kolkata",
    avatar: "SD",
    schedule: "Mon–Sat, 8 AM–12 PM",
    status: "Active",
  },
  {
    id: "w3",
    name: "Rahul Das",
    role: "Plumber",
    rating: 4.7,
    jobs: 198,
    distance: "1.8 km",
    eta: "6:00 PM",
    verified: { livePhoto: true, identity: true, coop: true, skill: false, bg: false },
    skills: ["Tap repair", "Pipe leakage", "Drain blockage", "Bathroom installation"],
    experience: "4 years",
    languages: ["Bengali"],
    area: "Within 8 km",
    availability: "Today: 4 PM – 8 PM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "Howrah Labour Cooperative",
    location: "Howrah",
    avatar: "RD",
  },
  {
    id: "w4",
    name: "Priya Sharma",
    role: "Cleaner",
    rating: 4.6,
    jobs: 156,
    distance: "1.2 km",
    eta: "Available",
    verified: { livePhoto: true, identity: true, coop: false, skill: false, bg: false },
    skills: ["Deep cleaning", "Office cleaning", "Kitchen cleaning"],
    experience: "3 years",
    languages: ["Hindi", "Bengali"],
    area: "Within 6 km",
    availability: "Today: 2 PM – 7 PM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "",
    location: "Durgapur",
    avatar: "PS",
  },
  {
    id: "w5",
    name: "Amit Mondal",
    role: "Porter",
    rating: 4.5,
    jobs: 89,
    distance: "3.2 km",
    eta: "On demand",
    verified: { livePhoto: true, identity: true, coop: true, skill: false, bg: false },
    skills: ["Heavy lifting", "Loading/unloading", "Moving assistance"],
    experience: "2 years",
    languages: ["Bengali"],
    area: "Within 12 km",
    availability: "Flexible",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "ABC Labour Cooperative",
    location: "Kolkata",
    avatar: "AM",
    schedule: "Flexible",
    status: "Active",
  },
  {
    id: "w6",
    name: "Salim Ansari",
    role: "Carpenter",
    rating: 4.8,
    jobs: 234,
    distance: "4.5 km",
    eta: "Tomorrow",
    verified: { livePhoto: true, identity: true, coop: true, skill: true, bg: false },
    skills: ["Furniture repair", "Cabinet making", "Door fitting", "Wood polishing"],
    experience: "7 years",
    languages: ["Hindi", "Urdu"],
    area: "Within 15 km",
    availability: "Tomorrow: 9 AM – 5 PM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "Siliguri Craftsman Cooperative",
    location: "Siliguri",
    avatar: "SA",
  },
  {
    id: "w7",
    name: "Maya Das",
    role: "Cook",
    rating: 4.9,
    jobs: 310,
    distance: "0.5 km",
    eta: "7:00 AM",
    verified: { livePhoto: true, identity: true, coop: true, skill: true, bg: true },
    skills: ["Bengali cuisine", "North Indian", "Tiffin service", "Catering"],
    experience: "10 years",
    languages: ["Bengali", "Hindi"],
    area: "Within 3 km",
    availability: "Mon–Sat: 7 AM – 10 AM",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "Mahila Labour Cooperative",
    location: "Kolkata",
    avatar: "MD",
  },
  {
    id: "w8",
    name: "Anita Roy",
    role: "Mehendi Artist",
    rating: 4.9,
    jobs: 178,
    distance: "2.8 km",
    eta: "Event day",
    verified: { livePhoto: true, identity: true, coop: false, skill: true, bg: false },
    skills: ["Bridal mehendi", "Arabic patterns", "Indo-Arabic", "Simple designs"],
    experience: "6 years",
    languages: ["Bengali", "Hindi"],
    area: "Within 20 km",
    availability: "Weekends, custom dates",
    phone: "+91 98765 XXXXX",
    phoneVisible: false,
    cooperative: "",
    location: "Kolkata",
    avatar: "AR",
  },
];

export const myWorkers = [
  { id: "w2", name: "Sita Devi", role: "Maid", schedule: "Mon–Sat", time: "8 AM–12 PM", status: "Active", avatar: "SD", rating: 4.9 },
  { id: "w5", name: "Amit Mondal", role: "Porter / Driver", schedule: "Flexible", time: "On demand", status: "Active", avatar: "AM", rating: 4.5 },
  { id: "ra", name: "Rahul Gardener", role: "Gardener", schedule: "Tue / Sat", time: "7 AM–9 AM", status: "Active", avatar: "RG", rating: 4.7 },
];

export const dailyJobs = [
  { id: "dj1", title: "Construction Helper", pay: "₹650/day", distance: "3 km", time: "8 AM–5 PM", date: "Today", urgency: "now", workers: 5, employer: "Haldia Infra Ltd." },
  { id: "dj2", title: "Loading / Unloading", pay: "₹550/day", distance: "2 km", time: "10 AM–4 PM", date: "Today", urgency: "now", workers: 3, employer: "Kolkata Warehousing" },
  { id: "dj3", title: "Painting Helper", pay: "₹700/day", distance: "5 km", time: "8 AM–5 PM", date: "Tomorrow", urgency: "tomorrow", workers: 2, employer: "Rainbow Painters" },
  { id: "dj4", title: "Event Setup Crew", pay: "₹600/day", distance: "4 km", time: "10 AM–10 PM", date: "Saturday", urgency: "weekend", workers: 8, employer: "Event Masters Pvt." },
];

export const notifications = [
  { id: "n1", type: "booking", title: "Booking Confirmed", body: "Ramesh Kumar will arrive at 5:30 PM today for tap repair.", time: "2 min ago", read: false, priority: "normal" },
  { id: "n2", type: "payment", title: "Payment Successful", body: "₹450 paid via UPI to Sita Devi. Invoice generated.", time: "Yesterday", read: true, priority: "normal" },
  { id: "n3", type: "welfare", title: "Welfare Fund Updated", body: "Your welfare fund balance is ₹2,400. Insurance active.", time: "2 days ago", read: true, priority: "low" },
  { id: "n4", type: "emergency", title: "Worker Running Late", body: "Rahul Das is running 20 minutes late. New ETA: 6:20 PM.", time: "Today", read: false, priority: "high" },
  { id: "n5", type: "training", title: "New Training Available", body: "AC Repair – Basic: Demand increased 42% in your area.", time: "3 days ago", read: true, priority: "low" },
  { id: "n6", type: "cooperative", title: "Governance Proposal", body: 'Vote on: "Allocate 5% surplus to emergency welfare fund."', time: "1 day ago", read: false, priority: "normal" },
];

export const adminStats = {
  activeWorkers: 847,
  todayBookings: 234,
  completedJobs: 189,
  pendingJobs: 45,
  workerEarnings: "₹1,24,800",
  coopFund: "₹18,650",
  avgRating: 4.7,
  completionRate: 94,
  cancellationRate: 3.2,
};

export const demandData = [
  { week: "W1", plumbing: 20, electrical: 30, cleaning: 45 },
  { week: "W2", plumbing: 22, electrical: 28, cleaning: 48 },
  { week: "W3", plumbing: 25, electrical: 35, cleaning: 52 },
  { week: "W4", plumbing: 28, electrical: 32, cleaning: 50 },
  { week: "W5", plumbing: 31, electrical: 38, cleaning: 55 },
  { week: "W6 (forecast)", plumbing: 35, electrical: 42, cleaning: 60 },
  { week: "W7 (forecast)", plumbing: 39, electrical: 46, cleaning: 65 },
  { week: "W8 (forecast)", plumbing: 43, electrical: 51, cleaning: 70 },
  { week: "W9 (forecast)", plumbing: 47, electrical: 56, cleaning: 76 },
];

export const zones = [
  { id: "A", name: "Zone A – Haldia", status: "critical", required: 25, available: 12, shortage: 13, color: "#DC2626" },
  { id: "B", name: "Zone B – Durgapur", status: "balanced", required: 18, available: 20, shortage: 0, color: "#16A34A" },
  { id: "C", name: "Zone C – Siliguri", status: "surplus", required: 8, available: 21, shortage: -13, color: "#CA8A04" },
  { id: "D", name: "Zone D – Howrah", status: "balanced", required: 22, available: 24, shortage: 0, color: "#16A34A" },
];

export const cooperativeNetwork = [
  { id: "coop1", name: "Haldia Labour Cooperative", zone: "Zone A", plumbers: 4, electricians: 6, maids: 12, status: "shortage" },
  { id: "coop2", name: "Kolkata Workers United", zone: "Zone B", plumbers: 18, electricians: 22, maids: 35, status: "surplus" },
  { id: "coop3", name: "Siliguri Craftsman Coop", zone: "Zone C", plumbers: 2, electricians: 8, maids: 6, status: "balanced" },
  { id: "coop4", name: "Howrah Labour Coop", zone: "Zone D", plumbers: 9, electricians: 14, maids: 18, status: "balanced" },
];

export const skillGaps = [
  { skill: "AC Technician", demand: "Critical", shortage: 24, benefit: "18 members could train" },
  { skill: "EV Technician", demand: "High", shortage: 15, benefit: "12 members could train" },
  { skill: "Solar Panel Installer", demand: "Medium", shortage: 8, benefit: "7 members could train" },
  { skill: "CCTV Installer", demand: "Medium", shortage: 6, benefit: "5 members could train" },
];

export const proposals = [
  {
    id: "p1",
    title: "Allocate 5% of monthly surplus to emergency worker welfare",
    proposer: "Kavita Mondal",
    date: "28 Aug 2026",
    yes: 73,
    no: 27,
    voted: 82,
    total: 126,
    status: "Active",
  },
  {
    id: "p2",
    title: "Introduce cooperative equipment pool for power tools",
    proposer: "Suresh Patel",
    date: "15 Aug 2026",
    yes: 91,
    no: 9,
    voted: 118,
    total: 126,
    status: "Passed",
  },
  {
    id: "p3",
    title: "Reduce platform commission from 12% to 10% for members",
    proposer: "Rekha Das",
    date: "10 Aug 2026",
    yes: 61,
    no: 39,
    voted: 105,
    total: 126,
    status: "Passed",
  },
];

export const equipment = [
  { id: "e1", name: "Drill Set #12", category: "Power Tools", status: "Available", returnDate: null, borrower: null },
  { id: "e2", name: "Ladder #7 (8 ft)", category: "Safety Equipment", status: "Booked", returnDate: "4 Sep 2026", borrower: "Ramesh Kumar" },
  { id: "e3", name: "Electrical Testing Kit", category: "Testing Tools", status: "Available", returnDate: null, borrower: null },
  { id: "e4", name: "Pipe Wrench Set", category: "Plumbing Tools", status: "Available", returnDate: null, borrower: null },
  { id: "e5", name: "Pressure Washer", category: "Cleaning Equipment", status: "Booked", returnDate: "6 Sep 2026", borrower: "Priya Sharma" },
];

export const chatMessages = [
  { id: "m1", sender: "customer", text: "Hi Ramesh, are you on your way?", time: "5:02 PM" },
  { id: "m2", sender: "worker", text: "Yes, I'm on my way. Will be there in 15 minutes.", time: "5:03 PM" },
  { id: "m3", sender: "customer", text: "Okay, the tap is in the kitchen. The main pipe is leaking.", time: "5:04 PM" },
  { id: "m4", sender: "worker", text: "Got it. I have the required tools. See you soon!", time: "5:05 PM" },
];

export const workerSchedule = [
  { id: "s1", time: "08:00", endTime: "09:00", type: "job", title: "Fan repair — Sector 4", customer: "Ananya S." },
  { id: "s2", time: "09:00", endTime: "09:30", type: "travel", title: "Travel", distance: "3.2 km" },
  { id: "s3", time: "09:30", endTime: "10:30", type: "job", title: "Switch installation — Park Street", customer: "Vikram M." },
  { id: "s4", time: "10:30", endTime: "11:00", type: "travel", title: "Travel", distance: "2.1 km" },
  { id: "s5", time: "11:00", endTime: "12:30", type: "job", title: "Home wiring — Salt Lake", customer: "Debjani R." },
  { id: "s6", time: "17:30", endTime: "18:15", type: "job", title: "Tap repair — Haldia", customer: "Ayush G." },
];

export const communityLeaderboard = [
  { rank: 1, name: "Ankit Gupta", points: 420, badge: "Community Builder" },
  { rank: 2, name: "Priya Bose", points: 380, badge: "Worker Champion" },
  { rank: 3, name: "Rahul Sen", points: 315, badge: "Verified Contributor" },
  { rank: 4, name: "You", points: 120, badge: null },
];
